- start_x: 6.3
  start_y: 1.15
  start_yaw: 0.0554984
  ball_x: 11.25
  ball_y: 6.8
  path:
    - id: 1
      robot: yes
    - id: 13
      robot: no
    - id: 19
      robot: yes
  extra_robots: []
  max_duration: 300 #seconds
  tutorial_duration: 30 #seconds
- start_x: 27.1
  start_y: 45.5
  start_yaw: 0.0767736
  ball_x: 45.55
  ball_y: 31.05
  path:
    - id: 161
      robot: yes
    - id: 151
      robot: no
    - id: 135
      robot: yes
    - id: 127
      robot: no
    - id: 128
      robot: yes
    - id: 119
      robot: no
    - id: 114
      robot: no
    - id: 112
      robot: yes
    - id: 106
      robot: no
    - id: 109
      robot: no
  extra_robots: []
  max_duration: 300 #seconds
  tutorial_duration: 45 #seconds
