door_detector_costmap:
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 0.0
  static_map: true
  transform_tolerance: 0.5
  obstacle_range: 2.5
  raytrace_range: 3.0
  footprint: [[-0.4, -0.3], [0.2, -0.3], [0.2, 0.3], [-0.4, 0.3]]
  footprint_padding: 0.05
  inflation_radius: 0.55
  observation_sources: scan
  scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
