- corners: [[-4.8, 7.3], [-3.75, 7.35]]
  approach:
    - from: cor
      point: [-4.25, 8.15, -1.5708]
    - from: o3_502
      point: [-4.65, 6.35, 1.24905]
  name: d3_502
- corners: [[6.5, 7.3], [7.8, 7.2]]
  approach:
    - from: cor
      point: [7.2, 8.2, -1.5708]
    - from: o3_508
      point: [6.9, 6.35, 1.30455]
  name: d3_508
- corners: [[7.85, 7.2], [8.9, 7.2]]
  approach:
    - from: cor
      point: [8.45, 8.15, -1.48014]
    - from: o3_510
      point: [8.6, 6.25, 1.69515]
  name: d3_510
- corners: [[14.25, 7.25], [15.45, 7.25]]
  approach:
    - from: cor
      point: [14.9, 8.3, -1.67047]
    - from: o3_512
      point: [14.6, 6.15, 1.42191]
  name: d3_512
- corners: [[19.35, 6.15], [19.35, 3.6]]
  approach:
    - from: s3_516
      point: [20.3, 4.85, 3.14159]
    - from: cor
      point: [18.5, 4.85, 0]
  name: d3_5161
- corners: [[25.65, 7.2], [27, 7.25]]
  approach:
    - from: cor
      point: [26.5, 7.95, -1.81578]
    - from: s3_516
      point: [26.2, 6.3, 1.52915]
  name: d3_5162
- corners: [[37.05, 8.95], [37.05, 7.75]]
  approach:
    - from: l3_436
      point: [37.8, 8.35, 3.06482]
    - from: cor
      point: [36.25, 8.3, 0]
  name: d3_4361
- corners: [[34.6, 14.95], [34.6, 16.05]]
  approach:
    - from: l3_436
      point: [35.4, 15.4, 3.14159]
    - from: cor
      point: [33.55, 15.35, -0.124356]
  name: d3_4362
- corners: [[29.45, 14.45], [28.05, 14.45]]
  approach:
    - from: cor
      point: [28.8, 15.3, -1.5708]
    - from: o3_428
      point: [28.95, 13.7, 1.7976]
  name: d3_428
- corners: [[26.65, 14.45], [25.45, 14.45]]
  approach:
    - from: o3_426
      point: [26.05, 13.7, 1.67046]
    - from: cor
      point: [25.95, 15.35, -1.46014]
  name: d3_426
- corners: [[24.25, 14.55], [25.5, 14.45]]
  approach:
    - from: cor
      point: [25, 15.45, -1.5708]
    - from: l3_414b
      point: [24.7, 13.45, 1.50423]
  name: d3_414b1
- corners: [[23.3, 8.9], [25.5, 8.9]]
  approach:
    - from: cor
      point: [24.3, 8.35, 1.5708]
    - from: l3_414b
      point: [24.3, 9.9, -1.5708]
  name: d3_414b2
- corners: [[18, 13.2], [18, 14.4]]
  approach:
    - from: l3_414b
      point: [18.8, 13.9, 3.14159]
    - from: l3_414
      point: [17.25, 13.8, 0]
  name: d3_414b3
- corners: [[12.65, 13.15], [12.65, 14.45]]
  approach:
    - from: l3_414
      point: [13.35, 13.95, 3.14159]
    - from: l3_414a
      point: [11.9, 13.85, 0]
  name: d3_414a3
- corners: [[6.55, 8.9], [5.4, 8.9]]
  approach:
    - from: l3_414a
      point: [6.05, 9.85, -1.5708]
    - from: cor
      point: [5.85, 8.15, 1.31347]
  name: d3_414a2
- corners: [[5.5, 14.4], [7.65, 14.5]]
  approach:
    - from: cor
      point: [6.4, 15.25, -1.47113]
    - from: l3_414a
      point: [6.65, 13.4, 1.5708]
  name: d3_414a1
- corners: [[4.3, 14.5], [5.5, 14.5]]
  approach:
    - from: cor
      point: [4.95, 15.35, -1.64757]
    - from: o3_412
      point: [4.75, 13.7, 1.48013]
  name: d3_412
- corners: [[-8.65, 16.15], [-7.6, 16.2]]
  approach:
    - from: cor
      point: [-8.25, 15.45, 1.5708]
    - from: o3_402
      point: [-8.4, 17.2, -1.32582]
  name: d3_402
- corners: [[-7.6, 16.15], [-6.45, 16.05]]
  approach:
    - from: o3_404
      point: [-6.95, 17.25, -1.72345]
    - from: cor
      point: [-7.1, 15.1, 1.47113]
  name: d3_404
- corners: [[6.7, 16.1], [7.8, 16.2]]
  approach:
    - from: o3_416
      point: [7.05, 17.2, -1.47113]
    - from: cor
      point: [7.15, 15.3, 1.68145]
  name: d3_416
- corners: [[7.85, 16.15], [8.95, 16.1]]
  approach:
    - from: o3_418
      point: [8.5, 17, -1.97569]
    - from: cor
      point: [8.25, 15.4, 1.5708]
  name: d3_418
- corners: [[14.3, 16.1], [15.55, 16.2]]
  approach:
    - from: o3_420
      point: [14.65, 17.25, -1.50423]
    - from: cor
      point: [14.8, 15.3, 1.5708]
  name: d3_420
- corners: [[15.45, 16.1], [16.65, 16.15]]
  approach:
    - from: o3_422
      point: [16.15, 16.9, -1.97569]
    - from: cor
      point: [15.9, 15.25, 1.48014]
  name: d3_422
- corners: [[29.5, 16.1], [30.85, 16.2]]
  approach:
    - from: o3_430
      point: [30, 17.5, -1.49403]
    - from: cor
      point: [30.15, 15.25, 1.48765]
  name: d3_430
- corners: [[30.75, 16.15], [31.95, 16.2]]
  approach:
    - from: o3_432
      point: [31.5, 17.1, -1.98902]
    - from: cor
      point: [31.3, 15.25, 1.5708]
  name: d3_432
